# shifted to AWS bedrock model for testing purpose.
azure_openai:
  # These model values are now Bedrock model IDs.
  endpoint: "https://bsap-ml6s56gx-eastus2.cognitiveservices.azure.com/"
  api_version: "2024-12-01-preview"
  primary_deployment: "us.anthropic.claude-3-5-sonnet-20240620-v1:0"
  fallback_deployment: "us.anthropic.claude-3-haiku-20240307-v1:0"
  timeout: 30
  max_concurrency: 50



# azure_openai:
#   endpoint: "https://bsap-ml6s56gx-eastus2.cognitiveservices.azure.com/"
#   api_version: "2024-12-01-preview"
#   primary_deployment: "gpt-5.2-chat"
#   fallback_deployment: "gpt-4o-mini"
#   timeout: 30
#   max_concurrency: 50