redis:
  allow_local_redis: false
  local_tunnel_enabled: false
  tunnel_local_port: 6380
  tunnel_instance_id: "i-00ac2c35d69cd4b7a"
  app:
    host: "ai-redis-cache-vho1b2.serverless.use1.cache.amazonaws.com"
    port: 6379
    db: 0
    username: ""
    password: ""
    tls: true
    ssl_cert_reqs: "required"
    ssl_ca_certs: "/etc/ssl/certs/ca-certificates.crt"
    socket_connect_timeout_seconds: 3
    socket_timeout_seconds: 5
    namespace: "app"
  worker:
    host: "ai-redis-cache-vho1b2.serverless.use1.cache.amazonaws.com"
    port: 6379
    db: 0
    username: ""
    password: ""
    tls: true
    ssl_cert_reqs: "required"
    ssl_ca_certs: "/etc/ssl/certs/ca-certificates.crt"
    socket_connect_timeout_seconds: 3
    socket_timeout_seconds: 5
    namespace: "worker"
