redis:
  app:
    host: "localhost"
    port: 6379
    db: 0
    username: ""
    password: ""
    tls: false
    ssl_cert_reqs: "required"
    ssl_ca_certs: ""
    namespace: "app"
  worker:
    host: "localhost"
    port: 6379
    db: 0
    username: ""
    password: ""
    tls: false
    ssl_cert_reqs: "required"
    ssl_ca_certs: ""
    namespace: "worker"
